# Include the configuration file generated by ./configure
-include config.mk

# Fallback definitions in case the user runs make without running ./configure
CC ?= gcc
PREFIX ?= /usr/local
DEPS = gtk+-3.0 gstreamer-1.0 libcurl json-c
CFLAGS ?= -Wall -O2 $(shell pkg-config --cflags $(DEPS) 2>/dev/null)
LIBS ?= $(shell pkg-config --libs $(DEPS) 2>/dev/null) -lpthread

TARGET = radio_app
SRC = radio_app.c
OBJ = $(SRC:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $@ $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

install: $(TARGET)
	install -d $(DESTDIR)$(PREFIX)/bin
	install -m 755 $(TARGET) $(DESTDIR)$(PREFIX)/bin/$(TARGET)

clean:
	rm -f $(OBJ) $(TARGET)

distclean: clean
	rm -f config.mk

.PHONY: all clean distclean install
